from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4

SECTION = "Invoice properties"
COMPANY_KEY = "COMPANY"
COMPANY_ADRESS_KEY = "COMPANY_ADRESS"
COMPANY_POSTAL_CODE_KEY = "COMPANY_POSTAL_CODE"
COMPANY_CITY_KEY = "COMPANY_CITY"
PHONE_NUMBER_KEY = "PHONE_NUMBER"
CEO_KEY = "CEO"
BANK_KEY = "BANK"
ACCOUNT_NUMBER_KEY = "ACCOUNT_NUMBER"
COMPANY_ORGANIZATION_NUMBER_KEY = "COMPANY_ORGANIZATION_NUMBER"
EMAIL_KEY = "EMAIL"
IBAN_KEY = "IBAN"
BIC_KEY = "BIC"
INVOICE_NUMBER_KEY = "INVOICE_NUMBER"
PAYMENT_DAYS_KEY = "PAYMENT_DAYS"

CLIENT_KEY = "CLIENT"
CLIENT_ADRESS_KEY = "CLIENT_ADRESS"
CLIENT_POSTAL_CODE_KEY = "CLIENT_POSTAL_CODE"
CLIENT_CITY_KEY = "CLIENT_CITY"
CLIENT_NUMBER_KEY = "CLIENT_NUMBER"
CLIENT_REFERENCE_KEY = "CLIENT_REFERENCE"
CLIENT_ORGANIZATION_NUMBER_KEY = "CLIENT_ORGANIZATION_NUMBER"

PROPERTIES_FILE = "invoice.properties"

WIDHT, HEIGHT = A4
MARGIN = 0.5 * inch

LEFT = MARGIN
RIGHT = 5.5 * inch